# Access Code Controller
# Module Owner: Teacher - Access Code Management

# Handles HTTP requests for access code endpoints

from flask import Blueprint, request, jsonify
from app.utils.decorators import jwt_required_with_role, teacher_required
from app.modules.teacher.access_code_service import AccessCodeService
from app.models.user import UserRole

access_codes_bp = Blueprint('access_codes', __name__)


@access_codes_bp.route('/generate/<attempt_id>', methods=['POST'])
@teacher_required
def generate_access_code(current_user, attempt_id):
    """Generate a fresh access code for a quiz attempt"""
    try:
        access_code = AccessCodeService.generate_access_code(
            attempt_id, current_user.id)

        return jsonify({
            'message': 'Access code generated successfully',
            'access_code': access_code,
            'attempt_id': attempt_id
        }), 200

    except ValueError as e:
        return jsonify({'error': str(e)}), 400
    except Exception as e:
        return jsonify({'error': 'Failed to generate access code', 'details': str(e)}), 500


@access_codes_bp.route('/active', methods=['GET'])
@teacher_required
def get_active_access_codes(current_user):
    """Get all active access codes generated by the teacher"""
    try:
        active_codes = AccessCodeService.get_active_access_codes(
            current_user.id)

        return jsonify({
            'active_codes': active_codes,
            'count': len(active_codes)
        }), 200

    except Exception as e:
        return jsonify({'error': 'Failed to get active access codes', 'details': str(e)}), 500


@access_codes_bp.route('/revoke/<attempt_id>', methods=['POST'])
@teacher_required
def revoke_access_code(current_user, attempt_id):
    """Revoke an active access code"""
    try:
        success = AccessCodeService.revoke_access_code(
            attempt_id, current_user.id)

        if success:
            return jsonify({'message': 'Access code revoked successfully'}), 200
        else:
            return jsonify({'error': 'Access code not found or already expired'}), 404

    except Exception as e:
        return jsonify({'error': 'Failed to revoke access code', 'details': str(e)}), 500


@access_codes_bp.route('/verify/<attempt_id>', methods=['POST'])
@jwt_required_with_role()
def verify_access_code(current_user, attempt_id):
    """Verify an access code (for student use)"""
    try:
        data = request.get_json()
        access_code = data.get('accessCode')
        device_info = data.get('deviceInfo', {})

        if not access_code:
            return jsonify({'error': 'Access code is required'}), 400

        # Students can only verify their own attempts
        if current_user.role == UserRole.STUDENT:
            attempt = QuizAttempt.query.filter_by(
                id=attempt_id, student_id=current_user.id).first()
            if not attempt:
                return jsonify({'error': 'Unauthorized'}), 403

        success = AccessCodeService.verify_access_code(
            attempt_id, access_code, device_info)

        if success:
            return jsonify({'message': 'Access code verified successfully'}), 200
        else:
            return jsonify({'error': 'Invalid or expired access code'}), 401

    except Exception as e:
        return jsonify({'error': 'Failed to verify access code', 'details': str(e)}), 500
