"""Initial migration

Revision ID: 44b25531f631
Revises: 
Create Date: 2025-12-08 20:30:53.056420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44b25531f631'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt_history', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.alter_column('quiz_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('in_progress', 'submitted', 'graded', 'auto_submitted'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('started_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('submitted_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('archived_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_history_active'))
        batch_op.drop_index(batch_op.f('idx_history_quiz_student'))
        batch_op.drop_index(batch_op.f('idx_history_status'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.alter_column('user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('entity_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_action'))
        batch_op.drop_index(batch_op.f('idx_created_at'))
        batch_op.drop_index(batch_op.f('idx_user_id'))

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.alter_column('created_by',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_name'))
        batch_op.drop_index(batch_op.f('unique_class'))
        batch_op.create_index(batch_op.f('ix_classes_name'), ['name'], unique=False)

    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_data', sa.JSON(), nullable=True))
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.alter_column('entity_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('triggered_by',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('processed_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_events_created'))
        batch_op.drop_index(batch_op.f('idx_events_processed'))
        batch_op.drop_index(batch_op.f('idx_events_type'))
        batch_op.drop_column('metadata')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_data', sa.JSON(), nullable=True))
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.alter_column('user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('read_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('priority',
               existing_type=mysql.ENUM('low', 'medium', 'high'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'"))
        batch_op.alter_column('category',
               existing_type=mysql.ENUM('quiz', 'grade', 'system', 'attempt_reset', 'violation'),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'system'"))
        batch_op.alter_column('expires_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_is_read'))
        batch_op.drop_index(batch_op.f('idx_notifications_category'))
        batch_op.drop_index(batch_op.f('idx_notifications_expires'))
        batch_op.drop_index(batch_op.f('idx_notifications_priority'))
        batch_op.drop_index(batch_op.f('idx_user_id'))
        batch_op.drop_column('metadata')

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.alter_column('user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_token'))
        batch_op.drop_index(batch_op.f('idx_user_id'))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.alter_column('created_by',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_created_by'))
        batch_op.drop_index(batch_op.f('idx_difficulty'))
        batch_op.drop_index(batch_op.f('idx_topic'))
        batch_op.drop_index(batch_op.f('idx_type'))
        batch_op.create_index(batch_op.f('ix_questions_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_type'), ['type'], unique=False)

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.alter_column('quiz_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('started_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('submitted_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('reset_by',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('reset_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_attempts_reset'))
        batch_op.drop_index(batch_op.f('idx_quiz_id'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_student_id'))

    with op.batch_alter_table('quiz_classes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.alter_column('quiz_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('class_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('assigned_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_class_id'))
        batch_op.drop_index(batch_op.f('idx_quiz_id'))
        batch_op.drop_index(batch_op.f('unique_quiz_class'))

    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.alter_column('quiz_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('question_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_question_id'))
        batch_op.drop_index(batch_op.f('idx_quiz_id'))

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.alter_column('access_code',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=6),
               existing_nullable=False)
        batch_op.alter_column('start_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_access_code'))
        batch_op.drop_index(batch_op.f('idx_created_by'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.create_index(batch_op.f('ix_quizzes_status'), ['status'], unique=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.alter_column('user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('revoked_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_token'))
        batch_op.drop_index(batch_op.f('idx_user_id'))

    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.alter_column('attempt_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('question_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('graded_by',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('graded_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('answered_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_attempt_id'))
        batch_op.drop_index(batch_op.f('idx_question_id'))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('class_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('claimed_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_class_id'))
        batch_op.drop_index(batch_op.f('idx_reg_number'))
        batch_op.drop_index(batch_op.f('registration_number'))
        batch_op.create_index(batch_op.f('ix_students_registration_number'), ['registration_number'], unique=True)

    with op.batch_alter_table('teacher_classes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.alter_column('teacher_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('class_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('assigned_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_class_id'))
        batch_op.drop_index(batch_op.f('idx_teacher_id'))
        batch_op.drop_index(batch_op.f('unique_teacher_class'))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index(batch_op.f('idx_subject'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('last_login',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('idx_email'))
        batch_op.drop_index(batch_op.f('idx_role'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_data', sa.JSON(), nullable=True))
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.alter_column('attempt_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('detected_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('severity',
               existing_type=mysql.ENUM('low', 'medium', 'high'),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_attempt_id'))
        batch_op.drop_index(batch_op.f('idx_violation_type'))
        batch_op.drop_column('metadata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
        batch_op.create_index(batch_op.f('idx_violation_type'), ['violation_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_attempt_id'), ['attempt_id'], unique=False)
        batch_op.alter_column('severity',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('low', 'medium', 'high'),
               existing_nullable=True)
        batch_op.alter_column('detected_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('attempt_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.drop_column('extra_data')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('idx_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('last_login',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_subject'), ['subject'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('teacher_classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_teacher_class'), ['teacher_id', 'class_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_class_id'), ['class_id'], unique=False)
        batch_op.alter_column('assigned_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('class_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('teacher_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_registration_number'))
        batch_op.create_index(batch_op.f('registration_number'), ['registration_number'], unique=True)
        batch_op.create_index(batch_op.f('idx_reg_number'), ['registration_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_class_id'), ['class_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('claimed_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('class_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_attempt_id'), ['attempt_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('answered_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('graded_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('graded_by',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('question_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('attempt_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_token'), ['token'], unique=False)
        batch_op.alter_column('revoked_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quizzes_status'))
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_access_code'), ['access_code'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('created_by',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('access_code',
               existing_type=sa.String(length=6),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))

    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_question_id'), ['question_id'], unique=False)
        batch_op.alter_column('question_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('quiz_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))

    with op.batch_alter_table('quiz_classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_quiz_class'), ['quiz_id', 'class_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_class_id'), ['class_id'], unique=False)
        batch_op.alter_column('assigned_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('class_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('quiz_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_attempts_reset'), ['is_reset', 'reset_by'], unique=False)
        batch_op.alter_column('reset_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('reset_by',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('submitted_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('started_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('student_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('quiz_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_type'))
        batch_op.drop_index(batch_op.f('ix_questions_topic'))
        batch_op.drop_index(batch_op.f('ix_questions_difficulty'))
        batch_op.create_index(batch_op.f('idx_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('idx_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('idx_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('idx_created_by'), ['created_by'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('created_by',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_token'), ['token'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_expires'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_notifications_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('idx_is_read'), ['is_read'], unique=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('quiz', 'grade', 'system', 'attempt_reset', 'violation'),
               existing_nullable=True,
               existing_server_default=sa.text("'system'"))
        batch_op.alter_column('priority',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('low', 'medium', 'high'),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'"))
        batch_op.alter_column('read_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.drop_column('extra_data')

    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
        batch_op.create_index(batch_op.f('idx_events_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_events_processed'), ['processed'], unique=False)
        batch_op.create_index(batch_op.f('idx_events_created'), ['created_at'], unique=False)
        batch_op.alter_column('processed_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('triggered_by',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('entity_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))
        batch_op.drop_column('extra_data')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_name'))
        batch_op.create_index(batch_op.f('unique_class'), ['name', 'section', 'academic_year'], unique=True)
        batch_op.create_index(batch_op.f('idx_name'), ['name'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('created_by',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_action'), ['action'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('entity_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))

    with op.batch_alter_table('attempt_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_history_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_history_quiz_student'), ['quiz_id', 'student_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_history_active'), ['is_active'], unique=False)
        batch_op.alter_column('archived_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('submitted_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('started_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('in_progress', 'submitted', 'graded', 'auto_submitted'),
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('quiz_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text('uuid()'))

    # ### end Alembic commands ###
